- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: 64943e86417774b9d6ba63c74e00f8cc3e2119e0
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: check-symlinks
      exclude: CHANGELOG.md
    - id: requirements-txt-fixer
    - id: trailing-whitespace

- repo: local
  hooks:
    - id: shellcheck
      name: shellcheck
      entry: make shellcheck
      language: system
      files: \.sh$
