---

language: ruby
sudo: required

matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode7.3
      env:
        - CUSER=travis
        - CHOME=/Users/travis
        - INSTALL_GPGTOOLS=0
        - OS=darwin
        - RUN_LIST=base,dotfiles
    - os: osx
      osx_image: xcode7.3
      env:
        - CUSER=travis
        - CHOME=/Users/travis
        - INSTALL_DOTFILES=0
        - OS=darwin
        - RUN_LIST=dev
    - os: osx
      osx_image: xcode7.3
      env:
        - CUSER=travis
        - CHOME=/Users/travis
        - INSTALL_DOTFILES=0
        - OS=darwin
        - RUN_LIST=messaging,multimedia
    - os: linux
      env:
        - CUSER=travis
        - CHOME=/home/travis
        - DISTRIB=debian:jessie
        - INSTALL_DOTFILES=1
        - INSTALL_VIRTUALBOX=0
        - OS=linux
        - RUN_LIST=base,dotfiles
      services:
        - docker
    - os: linux
      env:
        - CUSER=travis
        - CHOME=/home/travis
        - DISTRIB=debian:jessie
        - INSTALL_DOTFILES=0
        - INSTALL_VIRTUALBOX=0
        - OS=linux
        - RUN_LIST=dev
      services:
        - docker
    - os: linux
      env:
        - CUSER=travis
        - CHOME=/home/travis
        - DISTRIB=debian:jessie
        - INSTALL_DOTFILES=0
        - INSTALL_VIRTUALBOX=0
        - OS=linux
        - RUN_LIST=multimedia
      services:
        - docker

before_script:
  - mkdir "$HOME/bin"
  - curl -Lso "$HOME/bin/shellcheck" https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.4/shellcheck
  - chmod +x "$HOME/bin/shellcheck"
  - export PATH=$HOME/bin:$PATH

script:
  - ./travis.sh
