---

language: bash
sudo: required
install:
  - sudo apt-get install zsh
before_script:
  - mkdir "$HOME/bin"
  - curl -Lso "$HOME/bin/shellcheck" https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.3/shellcheck
  - chmod +x "$HOME/bin/shellcheck"
  - git clone https://github.com/sstephenson/bats.git "$HOME/bats"
  - ln -s "$HOME/bats/libexec/bats" "$HOME/bin/bats"
  - export PATH=$PATH:$HOME/bin
script:
  - make test
